// admin/api/ — Versioned types from LearnLoop API OpenAPI specs
//
// Each file is auto-generated by scripts/generate-rust-types.py.
// `latest` always re-exports the newest version.

#[allow(dead_code, non_camel_case_types, clippy::derive_partial_eq_without_eq)]
pub mod v1_3_2;

pub use v1_3_2 as latest;
