// admin/api/ — Versioned types from LearnLoop API OpenAPI specs
//
// Auto-generated by sync-api.yml. Each v*.rs file corresponds to
// an API release. `latest` re-exports the newest version.

#[allow(dead_code, non_camel_case_types, clippy::derive_partial_eq_without_eq)]
pub mod v1_3_2;

#[allow(dead_code, non_camel_case_types, clippy::derive_partial_eq_without_eq)]
pub mod v1_6_0;

pub use v1_6_0 as latest;
