// glow/api/ — Versioned types from glow-api OpenAPI specs
//
// Each file is auto-generated by scripts/generate-rust-types.py.
// `latest` always re-exports the newest version.

#[allow(dead_code, non_camel_case_types, clippy::derive_partial_eq_without_eq)]
pub mod v0_4_0;

pub use v0_4_0 as latest;
